/home/xbabu/Desktop/share/shell/create_open_linux
/home/xbabu/Desktop/share/shell/create_open_linux/config.csv
/home/xbabu/Desktop/share/shell/create_open_linux/create_open_linux.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/Thunar
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/Thunar/accels.scm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/Thunar/uca.xml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gh/hosts.yml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-2.0
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-2.0/gtkfilechooser.ini
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-3.0
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-3.0/bookmarks
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-3.0/settings.ini
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-4.0
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/gtk-4.0/settings.ini
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/libinput-gestures.conf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/lxterminal
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/lxterminal/lxterminal.conf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm/default
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm/default/desktop-items-0.conf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm/default/pcmanfm.conf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm/images
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/pcmanfm/images/On_top_of_the_Rubihorn_by_Matthias_Niess.jpg
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages/0_package_control_loader.sublime-package.zip
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages/Package Control.sublime-package.zip
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages/Sublime Input.sublime-package
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages/SublimeMozcInput.sublime-package.zip
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Installed Packages/TerminalView.sublime-package.zip
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Local
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Local/Auto Save Session.sublime_session
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Local/Session.sublime_session
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/.gitignore
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/.no-sublime-package
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Context.sublime-menu
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Default (Linux).sublime-keymap
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Default (OSX).sublime-keymap
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Default (Windows).sublime-keymap
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Default.sublime-commands
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/LICENSE
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Main.sublime-menu
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/PS.bat
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/PS.ps1
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Side Bar.sublime-menu
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Terminal.py
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Terminal.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/Terminal.sublime-settings
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/changelog.md
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/hyper.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/iTerm.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/iTerm2-v3.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages/1.13.0.txt
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages/1.4.0.txt
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages/1.7.0.txt
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages/1.8.0.txt
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/messages.json
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/package-metadata.json
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/readme.md
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/Terminal/release.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User/Default (Linux).sublime-keymap
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User/Package Control.sublime-settings
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User/Package Control.user-ca-bundle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User/Preferences.sublime-settings
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/sublime-text/Packages/User/python37.sublime-build
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/synapse
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/synapse/config.json
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/terminal
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/terminal/accels.scm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/terminal/terminalrc
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfce4-taskmanager.rc
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfconf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfconf/xfce-perchannel-xml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfconf/xfce-perchannel-xml/pointers.xml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu/cimnt.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu/monitor_setting.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu/new-item.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu/rfmfromfm.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/file_manager_menu/terminal.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/cmdclick.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/lxrandr2.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/mnt_remote_pc.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/mscroll.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/rfmfrommenu.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/grobal_menu/tscroll.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminished-Bold.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminished-BoldOblique.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminished-Oblique.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminished-Regular.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminishedDiscord-Bold.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminishedDiscord-BoldOblique.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminishedDiscord-Oblique.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.fonts/RictyDiminishedDiscord-Regular.ttf
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.gtkrc-2.0
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/.imwheelrc
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/active_window.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/back_button.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/back_button_exec.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/down.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/exec_active_window.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/gdrive_rsync.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/gdrive_rsync3.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/gdrive_rsync_contents.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/google_chrome_lounch.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/lock_escape.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/search_word.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/seed_button.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/seed_button_exec.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/shutdown.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/thunar.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/myapp/up.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/home/startup.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursor.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/bd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/bottom_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/color-picker
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/copy
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/crossed_circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/crosshair
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dnd-ask
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dnd-copy
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dnd-link
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dnd-move
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dnd-none
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/dotbox
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/fd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/grabbing
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/left_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/link
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/lr_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/move
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/plus
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/question_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/right_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_down_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_left_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/tcross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/top_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/ul_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/ur_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-Black/index.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursor.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/bd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/bottom_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/color-picker
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/copy
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/crossed_circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/crosshair
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dnd-ask
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dnd-copy
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dnd-link
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dnd-move
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dnd-none
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/dotbox
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/fd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/grabbing
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/left_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/link
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/lr_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/move
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/plus
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/question_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/right_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_down_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_left_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/tcross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/top_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/ul_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/ur_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/DMZ-White/index.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/cmdclick_image.png
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/based_arrow_down
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/based_arrow_up
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/bottom_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/center_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/dot
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/dotbox
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/draped_box
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/fleur
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/gumby
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/left_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/right_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/shuttle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/top_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/handhelds/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursor.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/HDoubleArrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/VDoubleArrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/base_arrow_down
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/base_arrow_up
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/based_arrow_down
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/based_arrow_up
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/bd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/center_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/copy
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/cross_reverse
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/crossed_circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/crosshair
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/draft_large
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/draft_small
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/fd_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/fleur
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/hand
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/hand1
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/link
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/lr_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/move
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/plus
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/question_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_down_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_left_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/tcross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/top_left_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/ul_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/ur_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/lil-polar/index.theme
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/based_arrow_down
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/based_arrow_up
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/bottom_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/center_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/dot
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/dotbox
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/draped_box
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/fleur
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/gumby
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/left_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/right_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/shuttle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/top_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/redglass/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/X_cursor
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/base_arrow_down
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/base_arrow_up
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/boat
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/bottom_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/bottom_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/bottom_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/bottom_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/center_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/circle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/cross
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/dot
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/dot_box_mask
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/draped_box
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/exchange
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/fleur
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/gumby
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/hand1
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/hand2
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/left_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/left_ptr_watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/left_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/left_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/ll_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/lr_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/pencil
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/pirate
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/question_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/right_ptr
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/right_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/right_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sailboat
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_down_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_h_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_left_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_right_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_up_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sb_v_double_arrow
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/shuttle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/sizing
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/target
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/top_left_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/top_right_corner
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/top_side
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/top_tee
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/trek
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/ul_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/ur_angle
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/watch
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/icon_theme/whiteglass/cursors/xterm
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/images
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/images/logo
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/images/logo/green_ring_rogo.png
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/images/wallpapers
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/images/wallpapers/On_top_of_the_Rubihorn_by_Matthias_Niess.jpg
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/themes
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/themes/mint-y-icons_1.3.4_all.deb
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/bkep
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/bkno
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/cimnt.ini
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/exec_cimnt.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/execute.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/ini_edit.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/init_setting.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/tscroll_dir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/tscroll_dir/exec_tscroll.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cimnt_dir/tscroll_dir/util.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/add.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/chdir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/chdir/chdir.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/chdir/exec_add_chdir.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/delete.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/edit.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/exec_cmdclick.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/execute.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/images
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/images/cmdclick_image.png
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/index.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/add_chdir.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/add_cmd_ini.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/check_ini_file.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/delete_cmd.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/edit_ini_file.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/edit_lib
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/edit_lib/convert_input_value.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/edit_lib/edit_function.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/edit_lib/make_ini_contensts.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/input_gui.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/main_list.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/cmdclick_dir/lib/read_ini_to_cmd.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/dfbk_als_plupin
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/dfbk_als_plupin/include_als_plugin.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_exec
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_exec/difbk_label_select.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib/export_difbk_function.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib/export_difbk_function_copy.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib/include_als_base_function.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib/include_als_plugin_function.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_lib/include_difbk_function.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_sch_func
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/difbk_sch_func/contents_search.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_als.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_bk.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_clean.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_diff.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_help.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_lrs.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_ls.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_rs.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/difbk_dir/exec_dfbk_sch.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll_dir
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll_dir/check.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll_dir/exec_mscroll.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll_dir/imwheelrc
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/mscroll_dir/util.sh
/home/xbabu/Desktop/share/shell/create_open_linux/dirs/usrlocalbin/tscroll
/home/xbabu/Desktop/share/shell/create_open_linux/experiment
/home/xbabu/Desktop/share/shell/create_open_linux/experiment/file_manager_menu
/home/xbabu/Desktop/share/shell/create_open_linux/experiment/file_manager_menu/root_mousepad.desktop
/home/xbabu/Desktop/share/shell/create_open_linux/files
/home/xbabu/Desktop/share/shell/create_open_linux/files/.bashrc
/home/xbabu/Desktop/share/shell/create_open_linux/files/01-network_manager.yaml
/home/xbabu/Desktop/share/shell/create_open_linux/files/Default (Linux).sublime-keymap
/home/xbabu/Desktop/share/shell/create_open_linux/files/Preferences.sublime-settings
/home/xbabu/Desktop/share/shell/create_open_linux/files/audiorelay-0.22.1.deb
/home/xbabu/Desktop/share/shell/create_open_linux/files/autostart
/home/xbabu/Desktop/share/shell/create_open_linux/files/config
/home/xbabu/Desktop/share/shell/create_open_linux/files/drawio-amd64-15.7.3.deb
/home/xbabu/Desktop/share/shell/create_open_linux/files/haroopad-v0.12.2-i386.deb
/home/xbabu/Desktop/share/shell/create_open_linux/files/lightdm-gtk-greeter.conf
/home/xbabu/Desktop/share/shell/create_open_linux/files/lightdm.conf
/home/xbabu/Desktop/share/shell/create_open_linux/files/panel
/home/xbabu/Desktop/share/shell/create_open_linux/files/rc.xml
/home/xbabu/Desktop/share/shell/create_open_linux/files/smb.conf
/home/xbabu/Desktop/share/shell/create_open_linux/files/wakeonlan
/home/xbabu/Desktop/share/shell/create_open_linux/files/wolg
/home/xbabu/Desktop/share/shell/create_open_linux/files/wolg.service
/home/xbabu/Desktop/share/shell/create_open_linux/include
/home/xbabu/Desktop/share/shell/create_open_linux/include/dialog.sh
/home/xbabu/Desktop/share/shell/create_open_linux/include/uninstall.sh
